spring.application.name=indexmind-api

# puerto de ejecución del servidor
server.port=8080

# ruta personalizada para OpenAPI (JSON) y Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
