.git
.github

.venv
venv
env

**/__pycache__
**/*.pyc
**/*.pyo

*.ipynb
.ipynb_checkpoints

data
data/**

notebooks
notebooks/**

experiments
experiments/**

reports
reports/**

*.log

.pytest_cache
.mypy_cache

dist
build

# v1.1 remains in repository but is not needed
# inside the v1.2 container.
models/v1.1.0

.vscode
.idea

Thumbs.db
.DS_Store
